name: Terraform Planner

on:
  push:
    branches:
      - main # ou votre branche cible

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Terraform Init
      run: terraform init

    - name: Create temp_prod.tfvars from GitHub Secret
      run: |
        echo "${{ secrets.TFVARS_PROD }}" > temp_prod.tfvars


    - name: Terraform Plan
      run: terraform plan -var-file="temp_prod.tfvars"
