name: Terraform Validation

on:
  push:
    branches:
      - main # ou votre branche cible

jobs:
  terraform_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Terraform Validate
      run: terraform validate

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Terraform Lint
      run: tflint

    - name: Create temp_prod.tfvars from GitHub Secret
      run: |
        echo "${{ secrets.TFVARS_PROD }}" | base64 --decode > temp_prod.tfvars

    - name: Create temp_backend.tf from GitHub Secret
      run: |
        echo "${{ secrets.BACKEND_PROD }}" | base64 --decode > temp_backend.tf

    - name: Terraform Init
      run: terraform init -backend-config="temp_backend.tf"

    - name: Terraform Plan
      run: terraform plan -var-file="temp_prod.tfvars"
