name: Terraform Validation

on:
  push:
    branches:
      - main # ou votre branche cible

jobs:
  terraform_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Terraform Init
      run: terraform init -backend=false # Initialiser sans backend pour la validation

    - name: Terraform Validate
      run: terraform validate

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Terraform Lint
      run: tflint

    - name: Decode prod.tfvars
      run: echo "${{ secrets.PROD_TFVARS }}" | base64 -d > prod.tfvars
    
    - name: Run Terraform Plan
      run: terraform plan -var-file=prod.tfvars
