name: Terraform Validation

on:
  push:
    branches:
      - main # ou votre branche cible

jobs:
  terraform_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3

    - name: Create temp_backend.tfvars from GitHub Secret
      run: |
        echo "${{ secrets.BACKEND_PROD }}" | base64 --decode > temp_backend.tfvars

    - name: Terraform Init
      run: terraform init -backend-config="temp_backend.tfvars" -reconfigure

    - name: Terraform Validate
      run: terraform validate

    - name: Create secrets_prod.tfvars from GitHub Secret
      run: |
        echo "${{ secrets.SECRETS_PROD }}" | base64 --decode > secrets_prod.tfvars

    - name: Terraform Plan
      run: terraform plan -var-file="secrets_prod.tfvars" -var-file="configurations/prod.tfvars"